smart_search/urls.py
from django.contrib import admin
from django.urls import path,include
from smart_searchapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('',include('smart_searchapp.urls')),
    path('user/',include('user.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

smart_searchapp/urls.py
from django.urls import path
from . import views

app_name='smart_searchapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('product?<int:id>/',views.product_detail,name='product'),
]

user/urls.py
from django.urls import path
from . import views

app_name='user'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.userlogin,name='login'),
    path('logout/',views.userlogout,name='logout'),
    path('cart/',views.cart,name='cart'),
    path('add-to-cart/<int:id>/',views.add_to_cart,name='add_to_cart'),
    path('delete_from_cart/<int:id>/',views.delete_from_cart,name='delete_from_cart'),
    path('profile/',views.profile,name='profile'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add-to-wishlist/<int:id>',views.add_to_wishlist,name='add_to_wishlist'),
    path('add_to_wishlist/<int:id>',views.add_to_wishlist_before_login,name='add-to-wishlist'),
    path('remove-from-wishlist/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('remove/<int:id>',views.remove_from_wishlist_prodpage,name='remove'),
    path('feedback/',views.feedback,name='feedback')
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from smart_searchapp.models import Product
from django.core.validators import RegexValidator
from phone_field import PhoneField

# Create your models here.
class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name=models.CharField(max_length=20)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{12,13}$', message="Should be in the format: '+91(10 digits)'")
    phone=models.CharField(validators=[phone_regex], max_length=13, blank=True)

    def __str__(self):
        return self.user.username

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    products=models.ForeignKey(Product,on_delete=models.CASCADE,blank=True)    
    date=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    ordered=models.BooleanField(default=False)
    quantity=models.IntegerField(default=1)
    total=models.DecimalField(default=0.00,max_digits=8,decimal_places=2)

    def __str__(self):
        return self.user.username
    
class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)   
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True) 

    def __str__(self):
        return self.user.username

class Feedback(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    subject=models.CharField(max_length=100)
    message=models.CharField(max_length=200)

    def __str__(self):
        return self.subject
    
    

user/forms.py
from django import forms
from .models import UserInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    #password2=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=['username','email','password']

        """def clean(self):
            data=self.cleaned_data
            password=self.cleaned_data.get('password')
            password2=self.cleaned_data.get('password2')
            if password!=password2:
                raise forms.ValidationError('Password not matching')
            return data"""

class UserInfoForm(forms.ModelForm):
    class Meta():
        model=UserInfo
        fields=['name','phone']

    """def clean_phone(self):
        phone=self.cleaned_data.get('phone')
        if len(phone)<10 and len(phone)>10:
            raise forms.ValidationError("Enter 10 digit phone number")
        return phone  """  

user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import UserInfo,Cart,Wishlist,Feedback
from .forms import UserForm,UserInfoForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from smart_searchapp.models import Product
from django.utils import timezone
#from django.views.decorators.cache import cache_control


# Create your views here.
def register(request):

    registered=False
    if request.user.is_authenticated:
        return redirect('smart_searchapp:index')
    else:

        if request.method=='POST':
            user_form=UserForm(request.POST)
            user_info=UserInfoForm(request.POST)

            if user_form.is_valid() and user_info.is_valid():
                user=user_form.save()
                user.set_password(user.password)
                user.save()

                info=user_info.save()
                info.user=user
                info.save()

                #name=user_info.cleaned_data.get('name')
                #messages=success(request,'Account created successfully for' + name)

                registered=True
                return redirect('user:login')

            else:
                print(user_form.errors,user_info.errors)
        else:
            user_form=UserForm()
            user_info=UserInfoForm()

        return render(request,'user/register.html',{'user_form':user_form,'user_info':user_info,'registered':registered})

#@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def userlogin(request):
    
    if request.user.is_authenticated:
        return redirect('smart_searchapp:index')
    else:
        if request.method=='POST':
            username=request.POST.get('username')
            password=request.POST.get('password')
            
            user=authenticate(request,username=username,password=password)
            if user:
                if user.is_superuser:
                    login(request,user)
                    return redirect('admin:index')
                elif user.is_active:
                    login(request,user)
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    else:    
                        return redirect('smart_searchapp:index')
            else:
                messages.info(request,'Invalid credential')

        return render(request,'user/login.html')     

@login_required(login_url='user:login')
def userlogout(request):
    logout(request)
    return redirect('smart_searchapp:index')   

@login_required(login_url='user:login')
def cart(request):
    citem=Cart.objects.filter(user=request.user)
    subtotal=0
    if citem:
        for rate in citem:
            subtotal+=rate.products.rate
    return render(request,'user/cart.html',{'citem':citem,'subtotal':subtotal})    

@login_required(login_url='user:login')
def add_to_cart(request,id):
    itemid=get_object_or_404(Product,id=id)
    item=Cart.objects.filter(user=request.user,products_id=itemid)

    if item.count()==0:
        cart_item=Cart.objects.create(user=request.user,products=itemid,ordered=False)
        messages.info(request,"One item has been added to your cart") 
        return redirect("user:cart")
    else:
        messages.info(request,"Item already exists in the cart") 
        return redirect("user:cart")
    #cart_query=Cart.objects.filter(user=request.user,ordered=False)
    
    """if cart_query.exists():
        cartcheck=cart_query
        # check if the item is in the cart
        if cartcheck.products.filter(id=itemid).exists():
            cart_item=Cart.objects.create(user=request.user,products=itemid,ordered=False)
            cart_item.quantity+=1
            cart_item.save()
            messages.info(request,"Item quantity has been updated") 
            return redirect("user:cart")
        else:
            cart_item=Cart.objects.create(user=request.user,products=itemid,ordered=False)
            cart_item.save()
            messages.info(request,"This item has been added to your cart") 
            return redirect("user:cart")
    else:
            cart_item=Cart.objects.create(user=request.user,products=itemid,ordered=False)
            cart_item.save()
            messages.info(request,"This item has been added to your cart") 
            return redirect("user:cart") """

    """if cart_query.exists():
        cart=cart_query
        # check if the item is in the cart
        if cart.products.filter(id=item.id).exists():
            cart_item.quantity+=1
            cart_item.save()
            messages.info(request,"Item quantity has been updated")
            return redirect("user:cart")
        else:
            cart.add(cart_item)
            cart.save()
            messages.info(request,"This item has been added to your cart") 
            return redirect("user:cart")"""


@login_required(login_url='user:login')
def delete_from_cart(request,id):
    cartdel=Cart.objects.get(id=id).delete()
    #messages.success(request,'One item has been removed from cart')
    return redirect("user:cart")

@login_required(login_url='user:login')    
def profile(request):
    return render(request,'user/profile.html')

@login_required(login_url='user:login')
def wishlist(request):
    witem=Wishlist.objects.filter(user=request.user)
    return render(request,'user/wishlist.html',{'witem':witem})

@login_required(login_url='user:login')
def add_to_wishlist(request,id):
    itemid=get_object_or_404(Product,id=id)
    item=Wishlist.objects.filter(user=request.user,product_id=itemid)
    if item.count()==0:
        wishlist_item=Wishlist.objects.create(user=request.user,product=itemid)
        messages.info(request,"Added to your wishlist") 
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    else:
        messages.error(request,"Item already exists in your wishlist")  
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))     

@login_required(login_url='user:login')
def add_to_wishlist_before_login(request,id):
    itemid=get_object_or_404(Product,id=id)
    item=Wishlist.objects.filter(user=request.user,product_id=itemid)
    if item.count()==0:
        wishlist_item=Wishlist.objects.create(user=request.user,product=itemid)
        messages.info(request,"Added to your wishlist") 
        return redirect('user:wishlist')
    else:
        messages.error(request,"Item already exists in your wishlist")  
        return redirect('user:wishlist')           

@login_required(login_url='user:login')
def remove_from_wishlist(request,id):
    wdelete=Wishlist.objects.get(id=id).delete()
    return redirect('user:wishlist')

@login_required(login_url='user:login')
def remove_from_wishlist_prodpage(request,id):
    wdelete=Wishlist.objects.get(id=id).delete()
    messages.info(request,"Removed from your wishlist") 
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))      

@login_required(login_url='user:login')
def feedback(request):
    if request.method=='POST':
        subject=request.POST.get('subject')
        message=request.POST.get('message')
        feed=Feedback.objects.create(user=request.user,subject=subject,message=message)
        messages.info(request,'Your message has been sent')
    return render(request,'user/profile.html')   
       

templates/user/cart.html
{% extends 'smart_searchapp/header.html' %} {% load static %} {% static "pics" as pics %} {% block content %}
<div class="flex-product-container">
    <div class="flex-product-item table-responsive">
        {% if citem %}
        <h3 class="text-left">Check out</h3>
        {% for add in messages %}
        <div class="p-3 mb-2 bg-success text-white">{{ add }}</div>
        {% endfor %}
        <table class="table table-responsive-md table-borderless carttable">
            <thead class="thead-light">
                <tr>
                    <th>Item</th>
                    <th>Added on</th>
                    <th>Unit Price</th>
                    <!--<th>Quantity</th>
                <th>Total</th>-->

                </tr>
            </thead>
            {% for citem in citem %}
            <tr style="align-items: center;">
                <td>
                    <a href="{% url 'smart_searchapp:product' citem.products.id %}">
                        <img width="auto" height="200" src="{{ citem.products.img.url }}" alt="">
                        <p class="bg-link">{{ citem.products.prodname }}</p>
                    </a>
                </td>

                <td>{{ citem.date|date:"d M Y" }}</td>
                <td>{{ citem.products.rate }}</td>
                <!--<td>{{ citem.quantity }}</td>
                <td>{{ citem.total }}</td>-->
                <td>
                    <a href="{% url 'user:delete_from_cart' citem.id %}" title="Remove from cart?">
                        <p class="error"><span class="fa fa-remove"></span> </p>
                    </a>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2" class="text-right">Total Amount: </td>
                <td class="text-primary">{{subtotal}}.00</td>
            </tr>
            </tbody>
        </table>
        {% else %}
        <h3 style="margin-top: 100px;">Your cart is empty</h3>
        {% endif %}
        <a href="{% url 'smart_searchapp:index' %}" class="btn btn-warning"><span
                class="fa fa-arrow-alt-circle-left"></span> Continue shopping</a>
    </div>
</div>

<div class="totop">
    <button onclick="totop()" id="totop" class="btn" title="Click to return to top of the page"><span
            class="fa fa-angle-double-up"></span></button>
</div>
{% endblock %}

templates/user/login.html
{% extends 'smart_searchapp/header.html' %}{% block content %}

<div class="flex-product-container">
    <div class="flex-item login">
        <div class="">
            <form method="POST">
                {% csrf_token %}
                <div class="">
                    <div class="col mb-4">
                        <label for="name">Username</label>
                        <div class="input-group">
                            <div class="input-group-append">
                                <button class="btn btn-light"><span class="fa fa-user"></span></button>
                            </div>
                            <input type="text" name="username" id="name" class="form-control" required>
                        </div>
                    </div>
                    <div class="col mb-4">
                        <label for="password">Password</label>
                        <div class="input-group">
                            <div class="input-group-append">
                                <button class="btn btn-light"><span class="fa fa-key"></span></button>
                            </div>
                            <input type="password" name="password" id="password" class="form-control" required>
                        </div>
                    </div>
                    {% for message in messages %}
                    <p class="error"> {{message}}</p>
                    {% endfor %} {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}"> {% endif %}
                    <button class="btn btn-primary" type="submit">LogIn</button>
                </div>
            </form>
            <br>
            <p style="color: white;">New here ? <a href="{% url 'user:register' %}"><button class="btn btn-link">Register</button></a></p>
        </div>
    </div>
</div>

<div class="totop">
    <button onclick="totop()" id="totop" class="btn" title="Click to return to top of the page"><span class="fa fa-angle-double-up" ></span></button>
</div>
{% endblock%}

templates/user/profile.html
{% extends 'smart_searchapp/header.html' %} {% load static %} {% static "pics" as pics %} {% block content %}

<div class="container">
    <div class="row down">
        <div class="col">
            <img src="{% static 'images/user.jpg' %}" alt="" width="100" height="100">

            <p> {{ request.user.userinfo.name }} </p>
            <p> {{ request.user.email }} </p>
        </div>
        <div class="col">
            <h5>
                <button class="btn btn-light"><a href="{% url 'user:wishlist' %}">Go to Wishlist </a><span
                        class="fa fa-heart error"></span>
                </button>
            </h5>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <em>
                <h3>Leave a feedback</h3>
            </em> {% for msg in messages %}
            <p class="error"> {{msg}}</p>
            {% endfor %}
            <form action="/user/feedback/" class="container-feedback" method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                        <input type="text" id="email" class="form-control" value="{{ request.user.email }}" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input type="text" id="subject" class="form-control" required name="subject">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <input type="text" id="message" class="form-control height-text" required name="message">
                </div>
                <div>
                    <input type="submit" value="Send" class="btn btn-primary">
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/register.html
{% extends 'smart_searchapp/header.html' %}{% block content %}

<div class="flex-container">
    <br> {% if registered %}
    <h4>Successfully Registered</h4>
    {% else %}
    <div class="register">

        <form method="POST">
            {% csrf_token %}
            <div class="">
                <div class="col mb-3">
                    <label for="id_name">Name</label> {{ user_info.name }}
                </div>
                <em> {{ user_info.name.errors }}</em>
                <div class="col mb-3">
                    <label for="id_phone">Mobile</label> {{ user_info.phone }}
                </div>
                <em>{{ user_info.phone.errors }}</em>
                <div class="col mb-3">
                    <label for="id_username">Username</label> {{ user_form.username }}
                </div>
                <em> {{ user_form.username.errors }}</em>
                <div class="col mb-3">
                    <label for="id_email">Email</label> {{ user_form.email}}
                </div>
                <em>{{ user_form.email.errors }}</em>
                <div class="col mb-4">
                    <label for="id_password">Password</label> {{ user_form.password }}
                </div>
                <em>{{ user_form.password.errors }}</em>
                <!--<div class="col mb-4">
                    <label for="id_password2">Retype Password</label> {{ user_form.password2 }}
                </div>
                <em>{{ user_form.password2.errors }}</em>-->
            </div>
            <button class="btn btn-primary" type="submit" style="margin-left: 15px;">Register</button>
        </form>

        <div>
            <br>
            <p style="color: white;">Already have an account ?
                <a href="{% url 'user:login' %}"><button class="btn btn-link">LogIn</button> </a></p>
        </div>
    </div>
    {% endif %}
</div>

<div class="totop">
    <button onclick="totop()" id="totop" class="btn" title="Click to return to top of the page"><span
            class="fa fa-angle-double-up"></span></button>
</div>

<script>
    var fields = document.getElementsByTagName('input')
    for (var i in fields) {
        fields[i].className = 'form-control'
            //fields[i].style.borderColor = 'grey'
        if (i == 0) {
            continue
        } else {
            fields[i].style.borderRadius = '20px'
        }


    }
    //console.log(fields)
    var errfield = document.getElementsByTagName('em')
    for (var e in errfield) {
        errfield[e].style.color = 'red'
    }
    //console.log(errfield)
</script>

{% endblock%}

templates/user/wishlist.html
{% extends 'smart_searchapp/header.html' %} {% load static %} {% static "pics" as pics %} {% block content %}
<div class="container">
    {% if witem %}
    <em class="down text-left">
        <h3>Your Wishlist</h3>
    </em> {% for add in messages %}
    <div class="p-3 mb-2 bg-success text-white text-center">{{ add }}</div>
    {% endfor %}
</div>
<div class="wishlist-container">
    {% for witem in witem %}
    <div class="wishlist-item row">
        <div class=" witem">
            <a href="{% url 'smart_searchapp:product' witem.product.id %}">
                <img width="auto" height="200" src="{{ witem.product.img.url }}" alt="">
            </a>
        </div>
        <div class="col witem2">
            <a href="{% url 'smart_searchapp:product' witem.product.id %}">
                <h5 class="">{{ witem.product.prodname }}</h5>
            </a>
            <p>₹ {{ witem.product.rate }}</p>
            <a href="{% url 'user:remove_from_wishlist' witem.id %}" title="Remove from wishlist">Remove
                <span class="error fa fa-remove"></span>
            </a>
        </div>
    </div>
    {% endfor %} {% else %}
    <h3 style="margin-top: 100px;">Your wishlist is empty</h3>
    {% endif %}
    <a href="{% url 'smart_searchapp:index' %}" class="btn btn-warning"><span
            class="fa fa-arrow-alt-circle-left"></span> Continue shopping</a>
</div>

{% endblock %}