smart_search/urls.py
from django.contrib import admin
from django.urls import path,include
from smart_searchapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('',include('smart_searchapp.urls')),
    path('user/',include('user.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

smart_searchapp/urls.py
from django.urls import path
from . import views

app_name='smart_searchapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('product?<int:id>/',views.product_detail,name='product'),
]

user/urls.py
from django.urls import path
from . import views

app_name='user'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.userlogin,name='login'),
    path('logout/',views.userlogout,name='logout'),
    path('cart/',views.cart,name='cart'),
    path('add-to-cart/<int:id>/',views.add_to_cart,name='add_to_cart'),
    path('delete_from_cart/<int:id>/',views.delete_from_cart,name='delete_from_cart'),
    path('profile/',views.profile,name='profile'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add-to-wishlist/<int:id>',views.add_to_wishlist,name='add_to_wishlist'),
    path('add_to_wishlist/<int:id>',views.add_to_wishlist_before_login,name='add-to-wishlist'),
    path('remove-from-wishlist/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('remove/<int:id>',views.remove_from_wishlist_prodpage,name='remove'),
    path('feedback/',views.feedback,name='feedback')
]

smart_searchapp/models.py
from django.db import models

class Product(models.Model):
    prodid=models.CharField(max_length=10,unique=True)
    prodname=models.CharField(max_length=30)
    brand=models.CharField(max_length=20)
    img=models.ImageField(upload_to='pics')
    description=models.TextField() 
    rate=models.IntegerField()
    category=models.CharField(max_length=20)
    objects=models.Manager()
    def __str__(self):
        return self.prodname

smart_searchapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Product
#from . import forms
from django.db.models import Q
from django.contrib import messages
from user.models import Wishlist


def index(request):
    query=request.GET.get('query')
    query_audio=request.GET.get('audioquery')
    query_video=request.GET.get('objquery')

    qs=Product.objects.all().order_by('?')
    if query!='' and query is not None:
        qs=qs.filter(
            Q(prodname__icontains=query) | Q(description__icontains=query) | 
            Q(brand__icontains=query) | Q(category__icontains=query)
            )
    elif query_audio!='' and query_audio is not None:
        qs=qs.filter(
            Q(prodname__icontains=query_audio) | Q(description__icontains=query_audio) | 
            Q(brand__icontains=query_audio) | Q(category__icontains=query_audio)
            )  
    elif query_video!='' and query_video is not None:
        qs=qs.filter(
            Q(prodname__icontains=query_video) | Q(description__icontains=query_video) | 
            Q(brand__icontains=query_video) | Q(category__icontains=query_video)
            )          

    return render(request,'smart_searchapp/index.html',{'products':qs})


def product_detail(request,id):
    prod=get_object_or_404(Product,id=id)
    check=False
    if request.user.is_authenticated:
        witem=Wishlist.objects.filter(user=request.user,product_id=prod)
        if witem.count()==0:
            check=True
        return render(request,'smart_searchapp/product.html',{'product':prod,'check':check,'witem':witem})    
    return render(request,'smart_searchapp/product.html',{'product':prod,'check':check})

templates/smart_searchapp/header.html
<!DOCTYPE html> {% load static %} {% static "pics" as pics %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="/static/images/favicon.png" />
    <title> Smart Search</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
    <script src="{% static 'js/mobilenet.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark header " id="nav">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="px-5 navbar-brand" href="{% url 'index' %}">
            <h1>Smart Search</h1>
        </a>

        <div class="ml-5 collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item pr-3">
                    <form action="/" method="get" class="form-inline my-2 my-lg-0 ">
                        <div class="input-group">
                            <input type="search" name="query" class="form-control" placeholder="Search for products" style="padding-right: 9em;">
                            <div class="input-group-append">
                                <button class="btn btn-secondary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
                <li class="nav-item pr-3">
                    <!-- smart search button-->
                    <button class="navbar-btn btn btn-success my-2 my-sm-0" data-toggle="modal" data-target="#exampleModalCenter">Smart Search</button>
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header bg-primary">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Smart Shopping search</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <!-- modal body -->
                                <div class="modal-body">

                                    <div class="text-center">

                                        <button type="audiobtn" class="btn btn-info" data-toggle="modal" data-target="#modalAudio">Search by Audio <span
                                                class='fas fa-microphone'></span></button>
                                        <button id="videobtn" type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalVideo">Search by Video <span
                                                class='fas fa-camera'></span></button>

                                    </div>

                                    <!--Modal: Audio-->
                                    <div class="modal fade" id="modalAudio" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-lg" role="document">

                                            <!--Content-->
                                            <div class="modal-content">

                                                <!--Body-->
                                                <div class="modal-body mb-0 p-0">
                                                    <div class="embed-responsive">
                                                        <div class="pulse-loader">
                                                            <div></div>
                                                            <div></div>
                                                        </div>
                                                        <p class="text-center result"></p>
                                                        <p class="text-center output"></p>

                                                    </div>

                                                    <div class="modal-footer justify-content-center">
                                                        <div class="">

                                                            <form action="/" method="get" id="myForm">
                                                                <button id="startbtn" class="btn btn-success">Start</button>
                                                                <!--<button id="audiosearch" class="btn btn-primary" type="submit">Search</button>-->
                                                                <input type="hidden" name="audioquery" id="audioquery" required>
                                                            </form>
                                                        </div>
                                                        <script src="{% static 'js/audio_script.js' %}">
                                                        </script>
                                                    </div>

                                                </div>

                                                <!--Footer-->
                                                <div class="modal-footer justify-content-center">
                                                    <button type="button" class="btn btn-outline-primary btn-rounded btn-md " data-dismiss="modal">Close</button>
                                                </div>

                                            </div>
                                            <!--/.Content-->

                                        </div>
                                    </div>
                                    <!--Modal: Audio-->

                                    <!--Modal: Object-->
                                    <div class="modal fade" id="modalVideo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-lg" role="document">

                                            <!--Content-->
                                            <div class="modal-content">

                                                <!--Body-->
                                                <div class="modal-body mb-0 p-0">

                                                    <div class="modal-footer justify-content-center">
                                                        <video width="100%" id="video" autoplay muted></video>
                                                        <canvas id="canvas" style="display: none;"></canvas>
                                                        <div id="status"></div>
                                                        <div id="result"></div>
                                                        <div class="modal-footer">

                                                            <button id="start" class="btn btn-success">Start</button>
                                                            <button id="playbutton" class="btn btn-warning">Play/Pause</button>
                                                            <button id="stop" class="btn btn-danger">Stop</button>
                                                            <form action="/" method="get">
                                                                <button id="search" class="btn btn-primary" type="submit">Search</button>
                                                                <input type="hidden" name="objquery" id="objquery" required>
                                                            </form>
                                                        </div>
                                                        <script src="{% static 'js/object_script.js' %}">
                                                        </script>
                                                    </div>

                                                </div>

                                                <!--Footer-->
                                                <div class="modal-footer justify-content-center">
                                                    <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>
                                                </div>

                                            </div>
                                            <!--/.Content-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                {% if not user.is_authenticated %}

                <li class="nav-item dropdown">
                    <button class="btn btn-light text-dark btndrop" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Login
                    </button>

                    <div class="dropdown-menu hoverdrop">
                        <form action="/user/login/" class="px-4 py-3" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email">Username</label>
                                <input type="text" name="username" class="form-control" id="email" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                            </div>
                            {% for message in messages %}
                            <p> {{message}}</p>
                            {% endfor %}

                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </form>
                        <!--<a href="{% url 'user:login' %}" style="position:auto;margin-left: 23px;">
                            <button class="btn btn-primary" data-toggle="modal" data-target="#signupmodal">
                                Log in
                            </button></a> -->
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'user:register' %}" style="position:auto;margin-left: 23px;">
                            <button class="btn btn-info" data-toggle="modal" data-target="#signupmodal">
                                Sign up
                            </button></a>

                    </div>
                </li>

                {% else %}
                <li class="nav-item pr-lg-5">
                    <a href="{% url 'user:cart' %}"><button class="btn btn-cart"><span class="fa fa-shopping-cart">
                                Cart</span></button></a>
                </li>
                <li class="mr-5"></li>
                <li class="mr-5"></li>
                <li class="mr-5"></li>
                <li class="nav-item">
                    <a href="{% url 'user:profile' %}" class="nav-link">Hey! {{ request.user.userinfo.name }}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:logout' %}"><button class="btn btn-dark">Log out</button> </a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% block content %} {% endblock %}
</body>

</html>

templates/smart_searchapp/index.html
{% extends 'smart_searchapp/header.html' %} {% load static %} {% static "pics" as pics %} {% block content %}

<div class="new-container">
    {% if products%}
    <div class="flex-container">
        {%for i in products%}
        <a href="{% url 'smart_searchapp:product' id=i.id %}">
            <div class="flex-item product">

                <p> {{i.prodname}}</p>
                <div>
                    <img src="{{i.img.url}}" alt="Cant load image" style="max-width:100%;height:200px;">
                </div>

                <div>
                    <p style="margin-top: 25px;"> ₹ {{i.rate}}</p>
                </div>

            </div>
        </a>
        {%endfor%} {%else%}
        <div class="no-record">
            <img src="{% static 'images/oops.jpg' %}" alt="">
            <br>
            <p>No Items found</p>
        </div>
    </div>{%endif%}
</div>

<!--<div style="position: fixed;left:0;bottom:50%">
        <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">Smart Search</button>
</div>-->
<div class="totop">
    <button onclick="totop()" id="totop" class="btn" title="Click to return to top of the page"><span class="fa fa-angle-double-up" ></span></button>
</div>

{% endblock %}

templates/smart_searchapp/product.html
{% extends 'smart_searchapp/header.html' %} {% load static %} {% static "pics" as pics %} {% block content %}

<div class="new-container">
    <!--{% if product%} -->
    <div class="flex-product-container">
        <div class="col flex-product-item">
            <h5 style="color: rgba(35, 5, 41, 0.836);">{{product.prodname}}</h5>
            <br>
            <div>
                <img id="zoomin" src="{{ product.img.url }}" alt="Cant load image" onmousemove="zoomIn(event)" onmouseout="zoomOut()" style="max-width: 40%; max-height:auto;">
            </div>

            <div>
                <h5 style="margin-top: 25px;"> ₹ {{product.rate}}</h5>
                {% if not user.is_authenticated %}
                <button class="wishlist-icon">
                    <a href="{% url 'user:add-to-wishlist' product.id %}" class="text-danger " title="Add to Wishlist">
                        <span class="material-icons">favorite_border</span></a>
                </button> {% endif %} {% if check %}
                <button class="wishlist-icon">
                    <a href="{% url 'user:add_to_wishlist' product.id %}" class="text-danger " title="Add to Wishlist">
                        <span class="material-icons">favorite_border</span></a>
                </button> {% else %} {% for witem in witem %}
                <button class="wishlist-icon">
                    <a href="{% url 'user:remove' witem.id %}" class="text-danger " title="Remove from Wishlist">
                        <span class="fa fa-heart"></span></a>
                </button>{% endfor %} {% endif %} {% for wishadd in messages %}
                <br />
                <br />
                <div class="p-3 mb-2 bg-success text-white text-center">{{ wishadd }}</div>
                {% endfor %}
            </div>

        </div>
        <div id="">

        </div>
        <div class="col flex-product-item" id="preview">
            <div class="tab-content tabWrapper" id="prod">
                <h5>Product Information</h5>
                <table class="table table-striped">
                    <tbody>
                        <tr class="techSpecRow">
                            <td class="techSpecTD1">Brand</td>
                            <td class="techSpecTD2">
                                {{product.brand}}
                            </td>
                        </tr>
                        <tr class="techSpecRow">
                            <td class="techSpecTD1">Name</td>
                            <td class="techSpecTD2">
                                {{product.prodname}}
                            </td>
                        </tr>
                        <tr class="techSpecRow">
                            <td class="techSpecTD1">Category</td>
                            <td class="techSpecTD2">
                                {{product.category}}
                            </td>
                        </tr>
                        <tr class="techSpecRow">
                            <td class="techSpecTD1">Description</td>
                            <td class="techSpecTD2">
                                <a href="#description"><button class="btn btn-sm btn-link">View</button></a>
                            </td>
                        </tr>
                        <tr class="techSpecRow">
                            <td class="techSpecTD1">Rate</td>
                            <td class="techSpecTD2">₹ {{product.rate}}
                            </td>
                        </tr>
                    </tbody>
                </table>
                <br>
                <a href="{% url 'user:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>

                <div>
                    <!-- {% for message in messages %}
                    <p class="error"> {{message}}</p>
                    {% endfor %} -->
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="flex-product-container">
        <div class="col flex-product-item" id="description">
            <div>
                <h6 style="font-weight: bold; color:rgb(235, 100, 22);">Product description of {{product.prodname}}
                </h6>
                <pre>
                    <span class="prediv">
                    {{ product.description|linebreaks }}
                </span>
                </pre>
            </div>
        </div>
    </div>
</div>{%endif%}

<div class="totop">
    <button onclick="totop()" id="totop" class="btn" title="Click to return to top of the page"><span
            class="fa fa-angle-double-up"></span></button>
</div>

<script>
    function zoomIn(event) {
        var pre = document.getElementById("preview");
        pre.style.visibility = "visible";
        if ($('#zoomin').is(':hover')) {
            var img = document.getElementById("zoomin");
            var prod = document.getElementById("prod");
            prod.style.visibility = "hidden";
            pre.style.backgroundImage = "url('{{ product.img.url }}')";
        }

        var posX = event.offsetX;
        var posY = event.offsetY;
        pre.style.backgroundPosition = (-posX * 1.5) + "px " + (-posY * 1.5) + "px";

    }

    function zoomOut() {
        var pre = document.getElementById("preview");
        var prod = document.getElementById("prod");
        prod.style.visibility = "visible";
        pre.style.visibility = "hidden";
    }
</script>
{% endblock %}